// Error types
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_DRIVER = 'CLEAR_DRIVER';
export const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';
export const CLEAR_RESTAURANT = 'CLEAR_RESTAURANT';

// User types
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';
export const GET_CURRENT_USER = 'GET_CURRENT_USER';

// Driver types
export const DRIVER_ORDERS_LOADING = 'DRIVER_ORDERS_LOADING';
export const GET_DRIVER_ORDERS = 'GET_DRIVER_ORDERS'; 
export const ORDER_PICKED = 'ORDER_PICKED'; 
export const ORDER_DELIVERED = 'ORDER_DELIVERED'; 
export const DRIVER_ORDER_STATUS = 'DRIVER_ORDER_STATUS';

// Restaurant types
export const RESTAURANT_LOADING = 'RESTAURANT_LOADING';
export const GET_RESTAURANT_MENUS = 'GET_RESTAURANT_MENUS';
export const ADD_RESTAURANT_MENU = 'ADD_RESTAURANT_MENU';
export const UPDATE_RESTAURANT_MENU = 'UPDATE_RESTAURANT_MENU';
export const DELETE_RESTAURANT_MENU = 'DELETE_RESTAURANT_MENU';
export const GET_RESTAURANT_ORDERS = 'GET_RESTAURANT_ORDERS';
export const CANCEL_RESTAURANT_ORDER = 'CANCEL_RESTAURANT_ORDER';
export const RESTAURANT_ORDER_ACCEPT = 'RESTAURANT_ORDER_ACCEPT';
export const RESTAURANT_ORDER_READY = 'RESTAURANT_ORDER_READY';
export const RESTAURANT_ORDER_STATUS = 'RESTAURANT_ORDER_STATUS';

// Customer types
export const CUSTOMER_LOADING = 'CUSTOMER_LOADING';
export const GET_CUSTOMER_RESTAURANTS = 'GET_CUSTOMER_RESTAURANTS';
export const GET_CUSTOMER_MENUS = 'GET_CUSTOMER_MENUS';
export const GET_CUSTOMER_ORDERS = 'GET_CUSTOMER_ORDERS';
export const CREATE_ORDER = 'CREATE_ORDER';
