server:
  port: ${SERVER_PORT}
elasticsearch:
  host: ${ELASTIC_HOST}
  port: ${ELASTIC_PORT}

spring:
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_CONSUMER_SERVER}
      group-id: ${KAFKA_GROUP_ID}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cache:
    type: redis
    redis:
      time-to-live: ${CACHE_TTL}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
kafka:
  topic:
    save: ${SAVE_TOPIC}
    delete: ${DELETE_TOPIC}